name: Allure TestOps

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
    - name: Publish to Allure TestOps
      uses: allure-framework/allure-github-actions@v2.2.0
      with:
        allure-results: ./allure-results
        allure-commandline-version: 2.14.0
        allure-server-url: ${{ secrets.ALLURE_SERVER_URL }}
        allure-project-name: ${{ secrets.ALLURE_PROJECT_NAME }}
        allure-token: ${{ secrets.ALLURE_TOKEN }}