name: Allure TestOps
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  allure-publish:
    name: Publish test results to Allure TestOps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests and generate Allure report
        run: pytest --alluredir=./allure-results
      - name: Publish to Allure TestOps
        uses: allure-framework/allure-github-actions@v1.1.1
        with:
          server_url: http://127.0.0.1:2222
          project_name: test1
          access_token: ${{ secrets.ALLURE_TOKEN }}